name: 'main'

on:
  push:
    branches:
    - master
  pull_request:

jobs: 
  Terraform:
    name: 'Terraform-Terratest'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Terraform for testing
      uses: autero1/action-terraform@v0.1.0
      with:
          terraform_version: 0.12.21

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.6

    - name: Get dependencies
      run: |
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        else
          go get -v -t -d ./...  
        fi

    - name: Run terratest
      working-directory: test/${{ github.event.head_commit.message}}
      run: go test

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: |
       cd ${{ github.event.head_commit.message}}
       terraform init

    - name: Terraform Format
      run: |
       cd ${{ github.event.head_commit.message}}
       terraform fmt -check

    - name: Terraform Plan
      run: |
       cd ${{ github.event.head_commit.message}}
       terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: |
       cd ${{ github.event.head_commit.message}}
       terraform apply -auto-approve
       curl http://localhost:8000


  